name: weather_app
description: Teleport Flutter Home Assessment

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  carousel_slider: ^4.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_i18n: ^0.31.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.2
  intl: ^0.17.0
  json_serializable: ^6.1.4
  location: ^4.3.0
  logger: ^1.1.0
  permission_handler: ^8.3.0
  retrofit: ^3.0.1

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.0.17
  retrofit_generator: ^4.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/cities.json
    - assets/i18n/
    - assets/images/